In [26]:
import pandas as pd

In [27]:
df = pd.read_excel("data/Symposia-speakers - Formatted.xlsx", sheet_name="Chair-cochairs")

In [28]:
filt = df["email"].notna()
df = df[filt]
df.head()

,symposia,role,name_th,name_en,affiliation,email,affiliation_2,email_2,KN,IV,Unnamed: 10
1,"1. Semiconductors, Photonic Materials and Devices",Chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,Chiang Mai University,anucha.w@cmu.ac.th,NaN,NaN,NaN
2,NaN,co-chair,ศาสตราจารย์ ดร. วิษณุ เพชรภา,Prof. Dr. Wisanu Pecharapa,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,NaN,NaN,NaN
3,NaN,co-chair,ดร. ทศพร เลิศวณิชผล,Dr. Tossaporn Lertvanithphol,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,NaN,NaN,NaN
7,"2. Polymers, Biomaterials and Medical Devices",Chair,รองศาสตราจารย์ ดร. วินิตา บุณโยดม,Assoc. Prof. Dr. Winita Punyodom,Chiang Mai University,winitacmu@gmail.com,Chiang Mai University,winitacmu@gmail.com,NaN,NaN,NaN
13,"3. Biosensors, Sensors, Flexible, and Wearable...",Chair 1(KN),Prof. Jianguo Tang,Prof. Jianguo Tang,Qingdao University,jianguotangde@hotmail.com,NaN,NaN,3.0,3.0,NaN

In [29]:
df['key'] = df['name_en'].str.replace(".", "_").str.replace(" ", "_").str.strip().str.lower().str.replace("__", "_")
df

,symposia,role,name_th,name_en,affiliation,email,affiliation_2,email_2,KN,IV,Unnamed: 10,key
1,"1. Semiconductors, Photonic Materials and Devices",Chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,Chiang Mai University,anucha.w@cmu.ac.th,NaN,NaN,NaN,assoc_prof_dr_anucha_watcharapasorn
2,NaN,co-chair,ศาสตราจารย์ ดร. วิษณุ เพชรภา,Prof. Dr. Wisanu Pecharapa,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,NaN,NaN,NaN,prof_dr_wisanu_pecharapa
3,NaN,co-chair,ดร. ทศพร เลิศวณิชผล,Dr. Tossaporn Lertvanithphol,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,NaN,NaN,NaN,dr_tossaporn_lertvanithphol
7,"2. Polymers, Biomaterials and Medical Devices",Chair,รองศาสตราจารย์ ดร. วินิตา บุณโยดม,Assoc. Prof. Dr. Winita Punyodom,Chiang Mai University,winitacmu@gmail.com,Chiang Mai University,winitacmu@gmail.com,NaN,NaN,NaN,assoc_prof_dr_winita_punyodom
13,"3. Biosensors, Sensors, Flexible, and Wearable...",Chair 1(KN),Prof. Jianguo Tang,Prof. Jianguo Tang,Qingdao University,jianguotangde@hotmail.com,NaN,NaN,3.0,3.0,NaN,prof_jianguo_tang
14,NaN,Chair,ดร. อดิสร เตือนตรานนท์,Dr. Adisorn Tuantranont,TMEC,adisorn.tua@nstda.or.th\nadisorn.tuantranont@g...,TMEC,adisorn.tua@nstda.or.th\nadisorn.tuantranont@g...,NaN,NaN,NaN,dr_adisorn_tuantranont
18,NaN,Chair,ศาสตราจารย์ ดร.นราธิป วิทยากร,Prof. Dr. Naratip Vittayakorn,King Mongkut's Institute of Technology Ladkrabang,naratip.vi@kmitl.ac.th,King Mongkut's Institute of Technology Ladkrabang,naratip.vi@kmitl.ac.th,0.0,0.0,NaN,prof_dr_naratip_vittayakorn
19,NaN,co-chair,ศาสตราจารย์ ดร. ธีระชัย บงการณ์,Prof. Dr. Theerachai Bongkarn,Naresuan University,researchcmu@yahoo.com,Naresuan University,researchcmu@yahoo.com,NaN,NaN,NaN,prof_dr_theerachai_bongkarn
20,NaN,co-chair,รองศาสตราจารย์ ดร. ศศิพร ประเสริฐปาลิฉัตร,Assoc. Prof. Dr. Sasipohn Prasertpalichat,Naresuan University,sasipohnp@nu.ac.th,Naresuan University,sasipohnp@nu.ac.th,NaN,NaN,NaN,assoc_prof_dr_sasipohn_prasertpalichat
21,NaN,co-chair,ผู้ช่วยศาสตราจารย์ ดร. ฐิติรัตน์ จรุญสุข,Asst. Prof. Dr. Thitirat Charoonsuk,Srinakharinwirot University,thitiratc@g.swu.ac.th,Srinakharinwirot University,thitiratc@g.swu.ac.th,NaN,NaN,NaN,asst_prof_dr_thitirat_charoonsuk
23,NaN,Chair,ศาสตราจารย์ ดร. วินิช พรมอารักษ์,Prof. Dr. Vinich Promarak,VISTEC,vinich.p@vistec.ac.th,VISTEC,nstis.mhesi@gmail.com,NaN,NaN,NaN,prof_dr_vinich_promarak
24,NaN,co-chair,รองศาสตราจารย์ ดร. ดวงมณี ว่องรัตนะไพศาล,Assoc. Prof. Dr. Duangmanee Wongratanaphisan,Chiang Mai University,duangmanee.wong@cmu.ac.th,Chiang Mai University,duangmanee.wong@cmu.ac.th,0.0,NaN,NaN,assoc_prof_dr_duangmanee_wongratanaphisan
25,,co-chair,ผู้ช่วยศาสตราจารย์ ดร. พิชญ พัฒนสัตยวงศ์,Asst. Prof. Dr. Pichaya Pattanasattayavong,VISTEC,pichaya.p@vistec.ac.th,VISTEC,pichaya.p@vistec.ac.th,NaN,NaN,NaN,asst_prof_dr_pichaya_pattanasattayavong
26,NaN,co-chair,ดร. พิศิษฐ์ คำหน่อแก้ว,Dr. Pisist Kumnorkeaw,NANOTEC,pisist@nanotec.or.th,NANOTEC,pisist@nanotec.or.th,NaN,NaN,NaN,dr__pisist_kumnorkeaw
29,NaN,Chair,ดร. พินิจ กิจขุนทด,Dr. Pinit Kidkhunthod,Synchrotron Light Research Institute (Public O...,pinit@slri.or.th,Synchrotron Light Research Institute (Public O...,pinit@slri.or.th,NaN,NaN,NaN,dr_pinit_kidkhunthod
30,NaN,co-chair,ศาสตราจารย์ ดร. ศิริพร จึงสุทธิวงษ์,Prof. Dr. Siriporn Jungsuttiwong,Ubon Ratchathani University,siriporn.j@ubu.ac.th,Ubon Ratchathani University,siriporn.j@ubu.ac.th,NaN,NaN,NaN,prof_dr_siriporn_jungsuttiwong
31,NaN,co-chair,รองศาสตราจารย์ ดร. สุรเทพ เขียวหอม,Assoc. Prof. Dr. Soorathep Kheawhom,Chulalongkorn University,soorathep.k@chula.ac.th,Chulalongkorn University,soorathep.k@chula.ac.th,NaN,NaN,NaN,assoc_prof_dr_soorathep_kheawhom
32,NaN,co-chair,ผู้ช่วยศาสตราจารย์ ดร. ประสิทธิ์ พัฒนะนุวัฒน์,Asst. Prof. Dr. Prasit Pattananuwat,Chulalongkorn University,prasit.pat@chula.ac.th,Chulalongkorn University,prasit.pat@chula.ac.th,NaN,NaN,NaN,asst_prof_dr_prasit_pattananuwat
34,NaN,Chair,ดร. อัญชลี มโนนุกุล,Dr. Anchalee Manonukul,MTEC,anchalm@mtec.or.th,MTEC,anchalm@mtec.or.th,NaN,NaN,NaN,dr_anchalee_manonukul
35,NaN,co-chair,รองศาสตราจารย์ ดร. อรทัย จงประทีป,Assoc. Prof. Dr. Oratai Jongprateep,Kasetsart University,oratai.j@ku.ac.th,Kasetsart University,oratai.j@ku.ac.th,NaN,NaN,NaN,assoc_prof_dr_oratai_jongprateep
36,NaN,co-chair,ผู้ช่วยศาสตราจารย์ ดร. นิติ ยงวณิชย์,Asst. Prof. Dr. Niti Yongvanich,Silpakorn University,niti@su.ac.th,Silpakorn University,niti@su.ac.th,NaN,NaN,NaN,asst_prof_dr_niti_yongvanich
38,NaN,Chair,ศาสตราจารย์ ดร. สุปรีดิ์ พินิจสุนทร,Prof. Dr. Supree Pinitsoontorn,Khon Kaen University,psupree@kku.ac.th,Khon Kaen University,psupree@kku.ac.th,NaN,NaN,NaN,prof_dr_supree_pinitsoontorn
39,NaN,co-chair,รองศาสตราจารย์ ดร. วิยะดา หาญชนะ,Assoc. Prof. Viyada Harnchana,Khon Kaen University,viyada@kku.ac.th,Khon Kaen University,viyada@kku.ac.th,NaN,NaN,NaN,assoc_prof_viyada_harnchana_
42,NaN,Chair,ผู้ช่วยศาสตราจารย์ ดร. อิทธิพล ฟองแก้ว,Asst. Prof. Dr. Ittipon Fongkaew,Suranaree University of Technology,ittipon@sut.ac.th,Suranaree University of Technology,ittipon@sut.ac.th,NaN,NaN,NaN,asst_prof_dr_ittipon_fongkaew
46,NaN,Chair,รองศาสตราจารย์ ดร. ศิริธันว์ เจียมศิริเลิศ,Assoc. Prof. Dr. Sirithan Jiemsirilers,Chulalongkorn University,sirithan.j@chula.ac.th,Chulalongkorn University,sirithan.j@chula.ac.th,NaN,NaN,NaN,assoc_prof_dr_sirithan_jiemsirilers
47,NaN,co-chair,รองศาสตราจารย์ ดร. ปกรณ์ โอภาประกาสิต,Assoc. Prof. Dr. Pakorn Opaprakasit,Sirindhorn International Institute of Technolo...,pakorno@gmail.com,Sirindhorn International Institute of Technolo...,pakorno@gmail.com,NaN,NaN,NaN,assoc_prof_dr_pakorn_opaprakasit
48,NaN,co-chair,รองศาสตราจารย์ ดร. อรทัย จงประทีป,Assoc. Prof. Dr. Oratai Jongprateep,Kasetsart University,fengotj@ku.ac.th,Kasetsart University,fengotj@ku.ac.th,NaN,NaN,NaN,assoc_prof_dr_oratai_jongprateep
49,NaN,co-chair,ผู้ช่วยศาสตราจารย์ ดร. นิติ ยงวณิชย์,Asst. Prof. Dr. Niti Yongvanich,Silpakorn University,niti@su.ac.th,Silpakorn University,niti@su.ac.th,NaN,NaN,NaN,asst_prof_dr_niti_yongvanich
51,NaN,Chair,รองศาสตราจารย์ ดร. วรวัฒน์ มีวาสนา,Assoc. Prof. Dr. Worawat Meevasana,Suranaree University of Technology,worawat@sut.ac.th,Suranaree University of Technology,worawat@sut.ac.th,NaN,NaN,NaN,assoc_prof_dr_worawat_meevasana
52,NaN,co-chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,Chiang Mai University,anucha.w@cmu.ac.th,NaN,NaN,NaN,assoc_prof_dr_anucha_watcharapasorn
58,NaN,Chair,ดร. อัญชลี มโนนุกุล,Dr. Anchalee Manonukul,MTEC,anchalm@mtec.or.th,MTEC,anchalm@mtec.or.th,NaN,NaN,NaN,dr_anchalee_manonukul
59,NaN,co-chair,ศาสตราจารย์ ดร. หทัยกานต์ มนัสปิยะ,Prof. Dr. Hathaikarn Manuspiya,Petromat,hathaikarn.m@chula.ac.th,Petromat,hathaikarn.m@chula.ac.th,NaN,NaN,NaN,prof_dr_hathaikarn_manuspiya
60,NaN,co-chair,รองศาสตราจารย์ ดร. ศิริธันว์ เจียมศิริเลิศ,Assoc. Prof. Dr. Sirithan Jiemsirilers,Chulalongkorn University,sirithan.j@chula.ac.th,Chulalongkorn University,sirithan.j@chula.ac.th,NaN,NaN,NaN,assoc_prof_dr_sirithan_jiemsirilers
62,NaN,Chair,ศาสตราจารย์ ดร. จักรพงษ์ แก้วขาว,Prof. Dr. Jakrapong Kaewkhao,Nakorn Pathom Rajabhat University,mink110tablet@gmail.com,Nakorn Pathom Rajabhat University,mink110tablet@gmail.com,NaN,NaN,NaN,prof_dr_jakrapong_kaewkhao
63,NaN,co-chair,ศาสตราจารย์ ดร. นราธิป วิทยากร,Prof. Dr. Naratip Vittayakorn,King Mongkut's Institute of Technology Ladkrabang,naratip.vi@kmitl.ac.th,King Mongkut's Institute of Technology Ladkrabang,naratip.vi@kmitl.ac.th,NaN,NaN,NaN,prof_dr_naratip_vittayakorn
64,NaN,co-chair,รองศาสตราจารย์ ดร. สุชาติ โกทันย์,Assoc. Prof. Dr. Suchart Kothan,Chiang Mai University,suchart.kothan@cmu.ac.th,Chiang Mai University,suchart.kothan@cmu.ac.th,NaN,NaN,NaN,assoc_prof_dr_suchart_kothan
65,NaN,co-chair,รองศาสตราจารย์ ดร. ภัทรวจี ยะสะกะ,Assoc. Prof. Dr. Patarawagee Yasaka,Nakorn Pathom Rajabhat University,pyasaka@hotmail.com,Nakorn Pathom Rajabhat University,pyasaka@hotmail.com,NaN,NaN,NaN,assoc_prof_dr_patarawagee_yasaka

In [30]:
df.columns

Index(['symposia', 'role', 'name_th', 'name_en', 'affiliation', 'email',
       'affiliation_2', 'email_2', 'KN', 'IV', 'Unnamed: 10', 'key'],
      dtype='str')

In [31]:
df.to_excel('output_excel/data.xlsx', index=False)